#pragma config(Motor,  port1,           rightFlyWheel, tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           leftFlyWheel,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           lift,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           intakeSpinner, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftFrontDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftBackDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           rightFrontDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightBackDrive, tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[leftFlyWheel] =100;
motor[rightFlyWheel] =100;

wait1Msec(15000);

}
