#pragma config(Sensor, dgtl2,  led1,           sensorDigitalOut)
#pragma config(Sensor, dgtl4,  led2,           sensorDigitalOut)
#pragma config(Sensor, dgtl6,  led3,           sensorDigitalOut)
#pragma config(Sensor, dgtl8,  led4,           sensorDigitalOut)
#pragma config(Sensor, dgtl10, led5,           sensorDigitalOut)
#pragma config(Sensor, dgtl12, led6,           sensorDigitalOut)
#pragma config(Motor,  port1,           rightFlyWheel, tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           leftFlyWheel,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           lift,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           intakeSpinner, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftFrontDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftBackDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           rightFrontDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightBackDrive, tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

motor[leftFlyWheel] =90;
motor[rightFlyWheel] =90;

wait1Msec(5000);
motor[leftFlyWheel] =90;
motor[rightFlyWheel] =90;
motor[leftBackDrive] =127;
motor[rightFrontDrive] = 124;
motor[leftFrontDrive] =127;
motor[rightBackDrive] = 124;
motor[leftFlyWheel] =90;
motor[rightFlyWheel] =90;
wait1Msec(200);
motor[leftFlyWheel] =90;
motor[rightFlyWheel] =90;
motor[leftBackDrive] =0;
motor[rightFrontDrive] = 0;
motor[leftFrontDrive] =0;
motor[rightBackDrive] = 0;
motor[leftFlyWheel] =90;
motor[rightFlyWheel] =90;
wait1Msec(5000);
}
