#pragma config(Motor,  port1,           rightFlyWheel, tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           leftFlyWheel,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           lift,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           intakeSpinner, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftFrontDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftBackDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           rightFrontDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightBackDrive, tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int flydebounce=0;
	int flyspeed = 0;
	int flybtn=0;

	int liftdebounce = 0;
	int liftspeed = 0;
	int liftbtn = 0;
	while(1)
	{
		motor[leftBackDrive] = vexRT[Ch3]; // controls motors
		motor[leftFrontDrive] = vexRT[Ch3];
		motor[rightBackDrive] = vexRT[Ch2];
		motor[rightFrontDrive] = vexRT[Ch2];

		flybtn = vexRT[Btn5D]; //controls flywheel with toggle switch
		if(flybtn && (flybtn != flydebounce))
			flyspeed = flyspeed?0:127;  // speed is modified only if btn is pressed and was unpressed.
		motor[leftFlyWheel] = flyspeed;
		motor[rightFlyWheel] = flyspeed;
		flydebounce = flybtn;

		liftbtn = vexRT[Btn6D]; //controls lift and intake with toggle switch
		if(liftbtn && (liftbtn != liftdebounce))
			liftspeed = liftspeed?0:127;  // speed is modified only if btn is pressed and was unpressed.
		motor[lift] = liftspeed;
		motor[intakeSpinner] = liftspeed;
		liftdebounce = liftbtn;
	}


}
