#pragma config(Sensor, dgtl2,  led1,           sensorDigitalOut)
#pragma config(Sensor, dgtl4,  led2,           sensorDigitalOut)
#pragma config(Sensor, dgtl6,  led3,           sensorDigitalOut)
#pragma config(Sensor, dgtl8,  led4,           sensorDigitalOut)
#pragma config(Sensor, dgtl10, led5,           sensorDigitalOut)
#pragma config(Sensor, dgtl12, led6,           sensorDigitalOut)
#pragma config(Motor,  port1,           rightFlyWheel, tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           leftFlyWheel,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           lift,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           intakeSpinner, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftFrontDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftBackDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           rightFrontDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightBackDrive, tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{

	motor[leftFlyWheel] = 90;
 motor[rightFlyWheel] =90;
 wait1Msec(60000);
	}




	/////////////////////////////////////////////////////////////////////////////////////////
	//
	//                                 User Control Task
	//
	// This task is used to control your robot during the user control phase of a VEX Competition.
	// You must modify the code to add your own robot specific commands here.
	//
	/////////////////////////////////////////////////////////////////////////////////////////

	task usercontrol()
	{

		int flydebounce=0; //set up variables
	int flyspeed = 0;
	int flybtn=0;

	int liftdebounce = 0;
	int liftspeed = 0;
	int liftbtn = 0;

	int intakedebounce = 0;
	int intakespeed = 0;
	int intakebtn = 0;

	int liftdirspeed = 0;

	int intakedirspeed =0;
	int flydirspeed = 110;


	while(1)
	{
		motor[leftBackDrive] = vexRT[Ch3]/2; // controls motors
		motor[leftFrontDrive] = vexRT[Ch3]/2;
		motor[rightBackDrive] = vexRT[Ch2]/2;
		motor[rightFrontDrive] = vexRT[Ch2]/2;

		if(vexRT[Btn7U]== true){ //controls flywheel speed with toggle switch

			flydirspeed = 110;
			flyspeed =110;
		}
		if (vexRT[Btn7R]== true){

			flydirspeed = 105;
			flyspeed = 105;
		}
		if (vexRT[Btn7D]== true){

			flydirspeed = 100;
			flyspeed = 100;
		}
		if (vexRT[Btn7L]== true){

			flydirspeed = 95;
			flyspeed = 95;
		}

		if (vexRT[Btn8U]== true){

			flydirspeed = 90;
			flyspeed = 90;
		}
		if (vexRT[Btn8R]== true){

			flydirspeed = 85;
			flyspeed = 85;
		}
		if (vexRT[Btn8D]== true){

			flydirspeed = 80;
			flyspeed = 80;
		}
		if (vexRT[Btn8L]== true){

			flydirspeed = 75;
			flyspeed = 75;
		}

			if(flydirspeed== 100)
		{
			SensorValue[led1] = false;
			SensorValue[led2] = false;
			SensorValue[led3] = false;

		}	else
			if(flydirspeed== 110 )
		{
			SensorValue[led1] = false;
			SensorValue[led2] = false;
			SensorValue[led3] = true;

		}	else
			if(flydirspeed== 120 )
		{
			SensorValue[led1] = false;
			SensorValue[led2] = true;
			SensorValue[led3] = true;

		} else
			if(flydirspeed ==127)
		{
			SensorValue[led1] = true;
			SensorValue[led2] = true;
			SensorValue[led3] = true;

		}
		if(vexRT[Btn6U]== true){ //intake and lift speed with toggle switch
			liftdirspeed = -127;
			intakedirspeed= 1;
		}
		else if(vexRT[Btn8U] == true){
			liftdirspeed = -127;
			intakedirspeed = -127;
		}

		else{
			liftdirspeed = 127;
			intakedirspeed = 127;
		}



		flybtn = vexRT[Btn5D]; //controls flywheel with toggle switch
		if(flybtn && (flybtn != flydebounce))
			flyspeed = flyspeed?0:flydirspeed;  // speed is modified only if btn is pressed and was unpressed.
		motor[leftFlyWheel] = flyspeed;
		motor[rightFlyWheel] = flyspeed;
		flydebounce = flybtn;

		liftbtn = vexRT[Btn6D]; //controls lift and intake with toggle switch
		if(liftbtn && (liftbtn != liftdebounce))
		{
			intakespeed = intakespeed?0:intakedirspeed;
			liftspeed = liftspeed?0:liftdirspeed; }  // speed is modified only if btn is pressed and was unpressed.
		motor[lift] = liftspeed;
		motor[intakeSpinner] = intakespeed;
		liftdebounce = liftbtn;


	}

		}







